name: phloem_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  get: ^4.6.6
  uuid: ^4.3.3
  google_sign_in: ^6.2.1
  introduction_screen: ^3.1.14
  firebase_auth: ^5.0.0
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_app_check: ^0.3.0
  provider: ^6.1.2
  youtube_player_flutter: ^9.0.1
  video_player: ^2.8.7
  chewie: ^1.8.1
  expansion_tile_card: ^3.0.0

  package_info_plus: ^8.0.0
  webview_flutter: ^4.8.0
  firebase_database: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
